### PR TITLE
Shiro authenticate for real

### PR DESCRIPTION
**Pull request by arthurdeschamps**
We finally figured out the mystery of shiro with @GiovannaTheo: we need to login in each and every module in order to get all the required cookies and keep being remembered by the services.

I've already secured the notifications and users services, posts still needs that.

### CODE REVIEW

**Comment by GiovannaTheo** [comment]
The Travis build somehow fails, please fix your code so that we can merge your PR @arthurdeschamps

**Comment by arthurdeschamps** [comment]
Don’t you ever tell me to fix my code again

**Comment by GiovannaTheo** [comment]
Too bad I'm the boss 😘

**Comment by arthurdeschamps** [comment]
Too bad you have no security if I quit 😂

**Pull request merged**
